require conf/distro/poky.conf

DISTRO = "minihil"
DISTRO_NAME = "MiniHIL Linux Distribution"
DISTRO_VERSION = "1.0"

# Use systemd as the init manager
INIT_MANAGER = "systemd"

# Accept restricted license for Raspberry Pi wireless firmware
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
