# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-minihil"
BBFILE_PATTERN_meta-minihil = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-minihil = "6"

LAYERDEPENDS_meta-minihil = "core raspberrypi"
LAYERSERIES_COMPAT_meta-minihil = "scarthgap"

# Global configuration defaults for MiniHIL platform
INIT_MANAGER = "systemd"
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
