name: minihil Build Checker (SIL)
on:
  push:
    branches: [ master ]
    paths:
      - 'sw/minihil/**/*.cpp'
      - 'sw/minihil/**/*.hpp'
      - 'sw/minihil/CMakeLists.txt'
  pull_request:
    branches: [ master ]
    paths:
      - 'sw/minihil/**/*.cpp'
      - 'sw/minihil/**/*.hpp'
      - 'sw/minihil/CMakeLists.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config nlohmann-json3-dev

      - name: Configure CMake
        run: |
          cmake -B sw/minihil/build -S sw/minihil

      - name: Build project
        run: |
          cmake --build sw/minihil/build --config Release
